name: CI
on: [push, pull_request]
jobs:
  lint_test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: flake8 linting
        run: poetry run flake8 .
      - name: black code formatting
        run: poetry run black . --check
      - name: mypy type checking
        run: poetry run mypy .
      - name: pytest
        run: poetry run pytest --cov=./ --cov-report=xml
      # TODO: uncomment when repo is public
      # - uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      #     files: ./coverage.xml
      #     fail_ci_if_error: true
      - name: build
        run: poetry build
